TestMIEApp/TestMIEApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestMIEApp.Models;

namespace TestMIEApp.Controllers
{
    public class TestController : Controller
    {
        private readonly ITestRepository _testRepository;
        public TestController(ITestRepository testRepository)
        {
            _testRepository = testRepository;
        }
        public IActionResult Start()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Start(PersonalData post_person)
        {
            if (ModelState.IsValid)
            {
                Instruction(post_person);
                return RedirectToAction("Instruction");
            }
            else
                return View(post_person);
        }

        public IActionResult Instruction(PersonalData person)
        {
            var test = _testRepository.DownloadTest(person);
            return View(test);
        }
        public IActionResult Test(PersonalData person)
        {
            var test = _testRepository.DownloadTest(person);
            return View(test);
        }

    }
}

TestMIEApp/TestMIEApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Test - Reading the Mind in the Eyes</title>
    <link href="~/favicon(1).ico" rel="icon" type="image/x-icon" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/StylePage.css" rel="stylesheet" type="text/css" media="screen" runat="server" />

</head>
<body>
    <div class="bg">
        <header>
            <nav class="navbar navbar-light" role="navigation">
                <div class="container-fluid">
                    <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#"><strong>Test.pl</strong></a>
                    </div>

                    <div class="collapse navbar-collapse" id="menu">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Test" asp-action="Start">Start</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="Statistics">Statistics</a></li>

                        </ul>
                    </div>
                </div>
            </nav>

            @RenderBody()
        </header>
        <footer>
            <div class="footer">
                <div>
                    <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
                </div>
                <p>&copy; 2019 - Test - Reading the Mind in the Eyes</p>
            </div>
        </footer>

    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>